#!/bin/bash
#pretty understandable tbh
# >> needs to be used to not overwrite, instead it added the ligne
output_file="testresult.txt"
echo "simple script showing ram usage and other infos"  > $output_file
echo "------------------------------------------------" >> $output_file
whoami >> $output_file
echo "------------------------------------------------" >> $output_file
date >> $output_file
echo "------------------------------------------------" >> $output_file
free -h >> $output_file